clone_folder: c:\projects\travis-test

os:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Win32
  - x64

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

test_script:
  - ctest -C Debug