# enable trusty
dist: trusty
sudo: required
# c++
language: cpp
# new stuff is good stuff
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=g++-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - clang-5.0
      env: COMPILER=clang-5.0
# test on clang and gcc
compiler:
  - clang
  - gcc
# lets go
script:
  - $COMPILER --version
  - mkdir build
  - cd build 
  - cmake .. -DCMAKE_CXX_COMPILER=$COMPILER
  - make
  - ctest
